In [101]:
import pandas as pd
import numpy as np
import catboost as catboost

from catboost import CatBoostRegressor

df_data = pd.read_csv("/content/driver_orders.csv")

modelDist = CatBoostRegressor()
modelDist.load_model("catboost_modelDist.cbm")

modelEarn = CatBoostRegressor()
modelEarn.load_model("catboost_modelEarn.cbm")

modelLocLocCity = CatBoostRegressor()
modelLocLocCity.load_model("catboost_modelLocLocCity.cbm")

modelTime = CatBoostRegressor()
modelTime.load_model("catboost_modelTime.cbm")

In [102]:
df_surge = pd.DataFrame({"city_id":[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5],"start_time":[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23],"surge_multiplier":[0.97, 0.98, 1.06, 1.14, 0.96, 0.97, 0.99, 1.36, 1.25, 1.25, 1.04,
       1.12, 1.01, 1.04, 1.04, 1.05, 1.34, 1.41, 1.29, 1.35, 0.98, 1.27,
       1.18, 1.3 , 1.08, 0.99, 1.13, 1.01, 1.08, 1.1 , 0.97, 1.24, 1.29,
       1.27, 1.01, 1.  , 1.02, 1.15, 1.04, 1.04, 1.3 , 1.29, 1.3 , 1.43,
       1.13, 1.13, 1.18, 1.22, 1.06, 0.99, 0.96, 1.11, 0.98, 1.03, 1.1 ,
       1.34, 1.28, 1.36, 1.15, 1.05, 1.13, 1.05, 1.03, 1.15, 1.4 , 1.28,
       1.36, 1.33, 1.05, 1.25, 1.17, 1.22, 1.  , 1.04, 1.13, 1.1 , 1.02,
       1.01, 1.07, 1.3 , 1.4 , 1.26, 1.13, 1.  , 1.11, 1.12, 0.99, 1.04,
       1.39, 1.33, 1.27, 1.4 , 1.05, 1.14, 1.11, 1.2 , 1.01, 1.11, 0.98,
       0.95, 1.13, 1.03, 1.12, 1.31, 1.38, 1.39, 0.97, 1.01, 0.99, 1.14,
       1.09, 1.14, 1.45, 1.41, 1.42, 1.44, 1.07, 1.26, 1.29, 1.19]})

In [103]:
df_data["pickup_lat"] = df_data["startLat"]
df_data["pickup_lon"] = df_data["startLon"]

df_data["drop_lat"] = df_data["endLat"]
df_data["drop_lon"] = df_data["endLon"]

In [104]:
df_aux = df_data[["pickup_lat","pickup_lon"]]

df_data["city_id"] = modelLocLocCity.predict(df_aux)
df_data["city_id"] = df_data["city_id"].astype(int)

In [105]:
df_data.head()

,driverLat,driverLon,rating,earnerType,experienceMonths,fuelType,isEv,vehicleType,startLat,startLon,...,endLon,startingTime,productType,paymentType,weatherType,pickup_lat,pickup_lon,drop_lat,drop_lon,city_id
0,50.004261,5.013873,0.0,0,3,2,False,1,52.710981,5.129187,...,5.643514,0,1,2,2,52.710981,5.129187,51.191658,5.643514,2
1,50.004261,5.013873,0.0,0,3,2,False,1,52.452585,4.236734,...,6.164507,3,0,0,2,52.452585,4.236734,52.390138,6.164507,3
2,50.004261,5.013873,0.0,0,3,2,False,1,52.416794,4.424362,...,5.065273,2,1,1,1,52.416794,4.424362,50.711553,5.065273,2
3,50.004261,5.013873,0.0,0,3,2,False,1,50.244222,6.614518,...,4.666000,4,0,2,0,50.244222,6.614518,51.514871,4.666000,3
4,50.004261,5.013873,0.0,0,3,2,False,1,51.052513,6.848737,...,6.796022,2,1,0,0,51.052513,6.848737,52.814118,6.796022,3

In [106]:
df_data["product"]=df_data["productType"]
df_data["vehicle_type"]=df_data["vehicleType"]
df_data["is_ev"]=df_data["isEv"]
df_data["start_time"]=df_data["startingTime"]

df_data = df_data.merge(df_surge,on=['city_id', 'start_time'],how='left')

df_data["payment_type"]=df_data["paymentType"]
df_data["weather"]=df_data["weatherType"]
df_data["earner_type"]=df_data["earnerType"]
df_data["fuel_type"]=df_data["fuelType"]
df_data["experience_months"]=df_data["experienceMonths"]

In [107]:
df_new = df_data[['city_id', 'product', 'vehicle_type', 'is_ev', 'start_time',
       'pickup_lat', 'pickup_lon', 'drop_lat', 'drop_lon', 'surge_multiplier',
       'payment_type', 'weather', 'earner_type', 'fuel_type',
       'experience_months', 'rating']]

In [108]:
df_ans = pd.DataFrame()

df_ans["dist_Order"] = modelDist.predict(df_new)
df_ans["time_Order"] = modelTime.predict(df_new)
df_ans["earn_Order"] = modelEarn.predict(df_new)

df_new["drop_lat"] = df_new["pickup_lat"]
df_new["drop_lon"] = df_new["pickup_lon"]

df_new["pickup_lat"] = df_data["driverLat"]
df_new["pickup_lon"] = df_data["driverLon"]

#print(df_new)

df_ans["dist_Pick"]  = modelDist.predict(df_new)
df_ans["time_Pick"]  = modelTime.predict(df_new)

df_ans["moneyPerHour"] = df_ans["earn_Order"]/((df_ans["time_Order"]+df_ans["time_Pick"])/60)

/tmp/ipython-input-3802110932.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["drop_lat"] = df_new["pickup_lat"]
/tmp/ipython-input-3802110932.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["drop_lon"] = df_new["pickup_lon"]
/tmp/ipython-input-3802110932.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["pickup_lat"] = df_data["driverLat"]
/tmp/ipython-input-3802110932.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["pickup_lon"] = df_data["driverLon"]

In [109]:
df_new

,city_id,product,vehicle_type,is_ev,start_time,pickup_lat,pickup_lon,drop_lat,drop_lon,surge_multiplier,payment_type,weather,earner_type,fuel_type,experience_months,rating
0,2,1,1,False,0,50.004261,5.013873,52.710981,5.129187,1.08,2,2,0,2,3,0.0
1,3,0,1,False,3,50.004261,5.013873,52.452585,4.236734,1.11,0,2,0,2,3,0.0
2,2,1,1,False,2,50.004261,5.013873,52.416794,4.424362,1.13,1,1,0,2,3,0.0
3,3,0,1,False,4,50.004261,5.013873,50.244222,6.614518,0.98,2,0,0,2,3,0.0
4,3,1,1,False,2,50.004261,5.013873,51.052513,6.848737,0.96,0,0,0,2,3,0.0
5,3,1,1,False,2,50.004261,5.013873,51.280781,6.215109,0.96,2,0,0,2,3,0.0
6,1,2,1,False,3,50.004261,5.013873,52.714032,5.009802,1.14,2,2,0,2,3,0.0
7,1,1,1,False,2,50.004261,5.013873,52.832134,5.008700,1.06,2,0,0,2,3,0.0
8,2,0,1,False,1,50.004261,5.013873,52.545877,5.513125,0.99,1,2,0,2,3,0.0
9,3,1,1,False,0,50.004261,5.013873,50.554470,6.728906,1.06,0,0,0,2,3,0.0
10,2,0,1,False,0,50.004261,5.013873,50.976941,4.927064,1.08,0,2,0,2,3,0.0
11,3,0,1,False,1,50.004261,5.013873,50.668732,6.807832,0.99,0,0,0,2,3,0.0
12,2,3,1,False,3,50.004261,5.013873,50.602819,4.718636,1.01,2,2,0,2,3,0.0
13,3,0,1,False,4,50.004261,5.013873,50.183014,6.647619,0.98,2,2,0,2,3,0.0
14,2,2,1,False,3,50.004261,5.013873,52.378102,5.851514,1.01,0,2,0,2,3,0.0
15,2,3,1,False,4,50.004261,5.013873,52.131479,4.923586,1.08,1,2,0,2,3,0.0
16,1,0,1,False,4,50.004261,5.013873,52.734427,4.704381,0.96,1,2,0,2,3,0.0
17,3,0,1,False,2,50.004261,5.013873,51.677079,4.313675,0.96,2,2,0,2,3,0.0
18,2,2,1,False,1,50.004261,5.013873,50.366133,4.620868,0.99,1,0,0,2,3,0.0
19,3,2,1,False,3,50.004261,5.013873,50.798324,6.433892,1.11,1,0,0,2,3,0.0
20,2,1,1,False,2,50.004261,5.013873,51.850686,4.945838,1.13,1,2,0,2,3,0.0
21,3,1,1,False,0,50.004261,5.013873,51.099975,5.087723,1.06,0,1,0,2,3,0.0
22,2,0,1,False,2,50.004261,5.013873,51.990941,4.717858,1.13,2,1,0,2,3,0.0
23,3,3,1,False,1,50.004261,5.013873,50.128694,5.767229,0.99,1,2,0,2,3,0.0
24,3,2,1,False,4,50.004261,5.013873,50.404270,6.723138,0.98,1,2,0,2,3,0.0
25,3,2,1,False,0,50.004261,5.013873,50.376020,6.742998,1.06,1,2,0,2,3,0.0
26,2,2,1,False,2,50.004261,5.013873,51.084673,4.375513,1.13,2,2,0,2,3,0.0
27,3,1,1,False,1,50.004261,5.013873,51.732068,6.854711,0.99,0,0,0,2,3,0.0
28,2,0,1,False,1,50.004261,5.013873,52.670228,5.437289,0.99,1,1,0,2,3,0.0
29,3,2,1,False,0,50.004261,5.013873,51.806255,6.644924,1.06,2,0,0,2,3,0.0
30,3,3,1,False,0,50.004261,5.013873,51.235839,5.821399,1.06,1,0,0,2,3,0.0
31,2,2,1,False,3,50.004261,5.013873,50.825831,4.683506,1.01,2,1,0,2,3,0.0
32,2,3,1,False,1,50.004261,5.013873,52.673928,5.923405,0.99,0,0,0,2,3,0.0
33,2,2,1,False,4,50.004261,5.013873,52.426201,6.992006,1.08,0,1,0,2,3,0.0
34,3,0,1,False,3,50.004261,5.013873,50.673618,4.004468,1.11,0,0,0,2,3,0.0
35,2,2,1,False,1,50.004261,5.013873,50.036678,4.465668,0.99,0,2,0,2,3,0.0
36,3,1,1,False,3,50.004261,5.013873,51.681180,5.144715,1.11,0,1,0,2,3,0.0
37,3,0,1,False,4,50.004261,5.013873,50.830451,5.785356,0.98,0,2,0,2,3,0.0

In [110]:
df_ans.head()

   dist_Order  time_Order  earn_Order  dist_Pick  time_Pick  moneyPerHour
0    6.365740   24.544490    6.575359   6.371515  24.475685      8.048146
1    6.754622   24.944947    9.339110   6.883683  23.909861     11.469631
2    6.346068   23.284426    7.868947   5.879433  25.309431      9.715978
3    6.445067   19.699089    9.082376   6.026352  18.032970     14.442428
4    6.406936   19.597733    7.554440   6.141414  15.935973     12.755956

In [111]:
df_ans.to_csv("output.csv",index=False)

In [114]:
df_ans[df_ans["moneyPerHour"]<df_ans["earn_Order"]]

Empty DataFrame
Columns: [dist_Order, time_Order, earn_Order, dist_Pick, time_Pick, moneyPerHour]
Index: []